= Trabajo Práctico: Bases de Datos I − Segundo Semestre 2022
Ávila Matías <leandroavmmo@gmail.com>; Perez Giannina <gianniperez2001@gmail.com>; Prieto Lucas <lucasprieto30@gmail.com>
v1, {docdate}. Docentes Hernan Czemerinski y Hernán Rondelli (COM-01)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

Este trabajo práctico consiste en crear una base de datos de tarjetas, en la cual se almacenarán datos de los *clientes*, sus respectivas *tarjetas* y *compras*, *comercios* en donde se realizaron las compras y los detalles de éstas. Además, estará incluida la información de los *consumos*, las *alertas*, los *rechazos* y los *cierres* de cada tarjeta. Para ello, se deberá crear una tabla correspondiente a cada una de las características solicitas e incorporar las PK’s y FK’s requeridas, que a su vez el usuario puede eliminar si así lo desea.

Se deben incluir también los siguientes stored procedures y/o triggers:

*Autorización de compra:* Valida o rechaza una compra, dependiendo si cumple o no los siguientes requisitos: La tarjeta debe ser válida y vigente, el número de tarjeta debe ser existente y el código de seguridad de ser correcto. Tamnién, el monto total de compras pendientes de pago más la compra a realizar no debe superar el límite de compra de la tarjeta.

*Generación del resumen:* Crea y guarda todos los datos necesarios para un resumen.

*Alertas a clientes:* Debe detectar y almacenar alertas para avisar a los clientes sobre posibles fraudes. Éstas consisten en comprobar que las tarjetas no superen dos compras dentro de un límite de tiempo, dependiendo del código postal en donde se realizaron dichas compras. Asimismo, suspender la tarjeta si ésta tiene dos rechazos por exceso de límite en el mismo día.

== Descripción

dificultades:
decimal (8,2)
timestamp - date

- Utilizamos la función substring() de SQL para poder determinar el valor de terminación dentro de la función generar_resumen().
En varios fields decidimos cambiar su tipo de int a serial, esto para poder incrementar su valor automáticamente.

- En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, las decisiones que se fueron tomando a lo largo
del trabajo práctico, y las cuestiones de diseño que consideren
importantes. También, se puede incluir una descripción general del programa—cómo
funciona.

- Cuando pruebo con una tarjeta no válida falla porque quiere insertar en rechazo
pero rechazo tiene una fk con nrotarjeta, y si no existe en la tabla tarjeta 
no lo permite.

== Implementación

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde.

Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
breve descripción, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos.

También se puede incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.
